language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
- npm run build:doc
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/doc
  on:
    branch: master
